CREATE TABLE posts (
	id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY, 
	title VARCHAR NOT NULL, 
	poster_id INTEGER NOT NULL, 
	FOREIGN KEY(poster_id) REFERENCES posters (id),
	text VARCHAR DEFAULT NULL, photo_urls VARCHAR DEFAULT NULL,
	likes INTEGER DEFAULT 0 NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, 
	modified_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);