CREATE TABLE posters (
	id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	login VARCHAR UNIQUE NOT NULL,
	nickname VARCHAR UNIQUE NOT NULL,
	hashed_password VARCHAR NOT NULL,
	is_active BOOLEAN DEFAULT TRUE NOT NULL,
	likes INTEGER DEFAULT 0 NOT NULL,
	created_at DATE DEFAULT CURRENT_DATE NOT NULL,
	photo_url VARCHAR DEFAULT NULL
);
